### ISSUE TITLE
Issues calling olap_reports/metrics/X

### ISSUE THREAD

**Issue by dhammond08** [CloudHealth/cht_api_guide#71]
Hello,

When attempting to call a report for the metrics class of reports - I am unable to get a return JSON and instead get a 404 error despite the "olap_reports/metrics" endpoint returning a list of links.

For example - this is one of the links returned from the listing of report links for the metrics category:
'https://chapi.cloudhealthtech.com/olap_reports/metrics/s3'

However, when attempting to call that report directly - I get a 404 using the standard GET request with a Content-Type of "application/json" and the usual api_key parameter with the correct key.  I can confirm I am able to pull other types of reports from other categories such as the "usage" category via these same methods but the metrics links don't appear to be working?

Apologies if I missed any specific documentation for this category but I did look and didn't see anything different for this.

**Comment by HumanistSerif** [comment]
Hello @dhammond08. You followed the prescribed path through the Reporting API endpoints, so rest assured that there’s nothing you’re missing. I checked with our engineers, and it turns out that none of the Metrics reports in the platform are queryable because they are not OLAP reports.

The `/metrics` endpoint should not be showing up when you query the `https://chapi.cloudhealthtech.com/olap_reports` endpoint. I have passed along this feedback to the engineering team so that they can clean up the response from the `/olap_reports` endpoint.

If you notice similar issues with the API, please reach out to support@cloudhealthtech.com for faster response.
